all:
  children:
    build:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        host: email-smtp.us-east-2.amazonaws.com
        username: "{{ lookup('env', 'EMAIL_USERNAME' }}"
        password: "{{ lookup('env', 'EMAIL_PASSWORD') }}"
        email_source: test@dragonslair.dev
        email_dest:
        - personone@dragonslair.dev
        - persontwo@dragonslair.dev

